### ISSUE TITLE
bin/cli.js is saved in a dos format

### ISSUE THREAD

**Issue by nathasm** [origin1tech/sequelize-cmd#5]
When trying to run this script from an OSX machine I was getting the following error:

    env: node\r: No such file or directory

Which made me realize that the format was in dos mode which means newlines had an additional '\r' character.

Consider using dos2unix to convert the file for broader acceptance.

**Comment by origin1tech** [comment]
have to look into that as line endings are all converted to unix style on commit/publish.

**Comment by saelfaer** [comment]
Curious you are posting a snippet you cut from the terminal when using sequelizecmd and you choose to paste the same line encountered in issue #4 ... are you suffering from the same issue as that one too or was it just a coincidence?

**Comment by origin1tech** [comment]
disclosure I haven't had time to dig into it but will later this week. significant updates/fixes coming which will get pushed here in a few days.

**Comment by nathasm** [comment]
@saelfaer It could be the same issue. I saw that my error specifically referenced node where your issue didn't seem to reference what or where the issue was.

Figured I would create a new issue, in case they weren't related.

**Comment by saelfaer** [comment]
@nathasm you're right to add a new issue, your's is actually not about the error per se, but more about the formatting of that file. It just struck me as odd that you got the same output from commands as I did.
I will await further investigation then from @origin1tech.

**Comment by origin1tech** [comment]
give me a day or two I'll get it sorted out fellas.

**Comment by origin1tech** [comment]
@nathsm @saelfaer I'm finally back to this. I should be able to push quite a few fixes here within a week or less. apologies for the delay.

**Comment by origin1tech** [comment]
Deprecated, Sequelize has decided to pull migration from core in favor of Umzug https://github.com/sequelize/umzug
